/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package learn;

import java.awt.Color;
import java.awt.Toolkit;
import java.awt.event.ActionListener;
import java.awt.event.WindowEvent;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.Calendar;
import java.util.TimerTask;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JRootPane;
import javax.swing.JTextArea;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author XavierTanXY
 */
public class HCIGUI extends javax.swing.JFrame {


    int defaultFontSize = 14;
    String defaultColor = "<Default>";
    
    int secondCounter = 0;
    int minuteCounter = 0;
    int projectCounter = 0;
    
    double totalHours = 0;

    Calendar cal;
    SimpleDateFormat sdf = new SimpleDateFormat("HH:mm");
    String startTime;
    String endTime;
    
    Boolean isIt = false;
    Boolean mode = false;
    
    String newProjectName;

    /**
     * Creates new form HCIGUI
     */
    public HCIGUI() {
        initComponents();
        
        categoryLabel.setVisible(false);
        pieLabel.setVisible(false);

        
        setupOptionChoice();
        setupColorOption();

    
    }
    
    //Add options
    public void setupOptionChoice() {
        
        optionChoice.add("Day");
        optionChoice.add("Week");
        optionChoice.add("Month");
        optionChoice.add("Year");
        
    }
    
    //Add colors
    public void setupColorOption() {
        
        colorOption.add("<Default>");
        colorOption.add("Ocean Blue>");
        colorOption.add("Dark Blue>");
        colorOption.add("Rose Red");
        colorOption.add("Grass Green");
        colorOption.add("Marble White");
        colorOption.add("Deep Black");
        colorOption.add("Banana Yellow");
        colorOption.add("Macaron Purple");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        sidePanel = new javax.swing.JPanel();
        btn_setting = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btn_dashboard = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        btn_projects = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        btn_export = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        btn_Add = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        panel_dashboard = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        descriptionTextField = new javax.swing.JTextField();
        btn_save = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        totalHoursLbl = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        categoryLabel = new javax.swing.JLabel();
        pieLabel = new javax.swing.JLabel();
        panel_tasks = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        dataTable = new javax.swing.JTable();
        optionChoice = new java.awt.Choice();
        jLabel13 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        panel_export = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        csvBtn = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        pdfBtn = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        excelBtn = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        panel_setting = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        colorLabel = new javax.swing.JLabel();
        colorOption = new java.awt.Choice();
        colorSaveBtn = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        fontSizeLabel = new javax.swing.JLabel();
        fontDecreaseBtn = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        fontInreaseBtn = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        secondTimer = new javax.swing.JLabel();
        minuteTimer = new javax.swing.JLabel();
        startButton = new javax.swing.JLabel();
        projectNames = new javax.swing.JComboBox<>();
        startDurationLabel = new javax.swing.JLabel();
        startDurationLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bg.setBackground(new java.awt.Color(98, 74, 134));

        sidePanel.setBackground(new java.awt.Color(54, 33, 89));
        sidePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_setting.setBackground(new java.awt.Color(64, 43, 100));
        btn_setting.setToolTipText("Setting");
        btn_setting.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_settingMousePressed(evt);
            }
        });
        btn_setting.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/learn/icons8-Settings-32.png"))); // NOI18N
        btn_setting.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 2, 40, 40));

        sidePanel.add(btn_setting, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 226, 61, 49));

        btn_dashboard.setBackground(new java.awt.Color(85, 65, 118));
        btn_dashboard.setToolTipText("Dashboard");
        btn_dashboard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_dashboardMousePressed(evt);
            }
        });
        btn_dashboard.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/learn/icons8-Home-32.png"))); // NOI18N
        btn_dashboard.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 40, 30));

        sidePanel.add(btn_dashboard, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 61, 61, 49));

        btn_projects.setBackground(new java.awt.Color(64, 43, 100));
        btn_projects.setToolTipText("Tasks");
        btn_projects.setPreferredSize(new java.awt.Dimension(120, 40));
        btn_projects.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_projectsMousePressed(evt);
            }
        });
        btn_projects.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/learn/icons8-Tasks-32.png"))); // NOI18N
        btn_projects.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 40, -1));

        sidePanel.add(btn_projects, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 116, 61, 49));

        btn_export.setBackground(new java.awt.Color(64, 43, 100));
        btn_export.setToolTipText("Export data in different formats");
        btn_export.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_exportMousePressed(evt);
            }
        });
        btn_export.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/learn/icons8-Sent-32.png"))); // NOI18N
        btn_export.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 2, 40, 40));

        sidePanel.add(btn_export, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 171, 61, 49));

        btn_Add.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_Add.setIcon(new javax.swing.ImageIcon(getClass().getResource("/learn/icons8-Add-32.png"))); // NOI18N
        btn_Add.setToolTipText("Add a new project");
        btn_Add.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_AddMouseClicked(evt);
            }
        });
        sidePanel.add(btn_Add, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 40, -1));

        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/learn/icons8-Help-32.png"))); // NOI18N
        jLabel12.setToolTipText("Help");
        sidePanel.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 520, 40, -1));

        jPanel3.setLayout(new java.awt.CardLayout());

        panel_dashboard.setBackground(new java.awt.Color(98, 74, 134));

        jPanel1.setBackground(new java.awt.Color(250, 250, 250));

        descriptionTextField.setBackground(new java.awt.Color(253, 253, 253));
        descriptionTextField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        descriptionTextField.setText("Task Description Here...");
        descriptionTextField.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        descriptionTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                descriptionTextFieldKeyTyped(evt);
            }
        });

        btn_save.setIcon(new javax.swing.ImageIcon(getClass().getResource("/learn/OpacSave.png"))); // NOI18N
        btn_save.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_saveMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(descriptionTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 765, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_save)
                .addGap(29, 29, 29))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(descriptionTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_save, javax.swing.GroupLayout.PREFERRED_SIZE, 51, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(250, 250, 250));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel8.setText("Total Hours:");

        totalHoursLbl.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        totalHoursLbl.setText("0 Hours");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(204, 204, 204));
        jLabel10.setText("SINCE 0 DAYS AGO");

        categoryLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/learn/NEWLABEL.PNG"))); // NOI18N

        pieLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/learn/NEWPIE.PNG"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(totalHoursLbl)
                    .addComponent(jLabel10)
                    .addComponent(categoryLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pieLabel)
                .addGap(151, 151, 151))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(pieLabel))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(totalHoursLbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(categoryLabel)))
                .addGap(471, 471, 471))
        );

        javax.swing.GroupLayout panel_dashboardLayout = new javax.swing.GroupLayout(panel_dashboard);
        panel_dashboard.setLayout(panel_dashboardLayout);
        panel_dashboardLayout.setHorizontalGroup(
            panel_dashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panel_dashboardLayout.setVerticalGroup(
            panel_dashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_dashboardLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.add(panel_dashboard, "card2");

        panel_tasks.setBackground(new java.awt.Color(255, 255, 255));

        dataTable.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        dataTable.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        dataTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tasks", "Date", "Start", "End", "Duration (Hours)"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        dataTable.setGridColor(new java.awt.Color(255, 255, 255));
        jScrollPane1.setViewportView(dataTable);
        if (dataTable.getColumnModel().getColumnCount() > 0) {
            dataTable.getColumnModel().getColumn(0).setResizable(false);
            dataTable.getColumnModel().getColumn(1).setResizable(false);
            dataTable.getColumnModel().getColumn(2).setResizable(false);
            dataTable.getColumnModel().getColumn(3).setResizable(false);
            dataTable.getColumnModel().getColumn(4).setResizable(false);
        }

        optionChoice.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel13.setForeground(java.awt.SystemColor.controlShadow);
        jLabel13.setText("Tasks");

        jPanel5.setBackground(new java.awt.Color(235, 235, 235));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Category");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addComponent(jLabel1)
                .addContainerGap(74, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel6.setBackground(new java.awt.Color(235, 235, 235));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("General");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(75, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(71, 71, 71))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel5)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panel_tasksLayout = new javax.swing.GroupLayout(panel_tasks);
        panel_tasks.setLayout(panel_tasksLayout);
        panel_tasksLayout.setHorizontalGroup(
            panel_tasksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_tasksLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_tasksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_tasksLayout.createSequentialGroup()
                        .addGroup(panel_tasksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 765, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_tasksLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(43, 43, 43)
                                .addComponent(optionChoice, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())
                    .addGroup(panel_tasksLayout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        panel_tasksLayout.setVerticalGroup(
            panel_tasksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_tasksLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_tasksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_tasksLayout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addGap(18, 124, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_tasksLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(panel_tasksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(optionChoice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(13, 13, 13)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel3.add(panel_tasks, "card2");

        panel_export.setBackground(new java.awt.Color(250, 250, 250));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel7.setForeground(java.awt.SystemColor.controlShadow);
        jLabel7.setText("Export To");

        csvBtn.setBackground(new java.awt.Color(98, 74, 134));
        csvBtn.setToolTipText("Export to CSV");
        csvBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                csvBtnMouseClicked(evt);
            }
        });

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/learn/icons8-CSV-64.png"))); // NOI18N

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(204, 255, 255));
        jLabel16.setText("CSV");

        javax.swing.GroupLayout csvBtnLayout = new javax.swing.GroupLayout(csvBtn);
        csvBtn.setLayout(csvBtnLayout);
        csvBtnLayout.setHorizontalGroup(
            csvBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(csvBtnLayout.createSequentialGroup()
                .addGroup(csvBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(csvBtnLayout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(jLabel16))
                    .addGroup(csvBtnLayout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(jLabel15)))
                .addContainerGap(53, Short.MAX_VALUE))
        );
        csvBtnLayout.setVerticalGroup(
            csvBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(csvBtnLayout.createSequentialGroup()
                .addContainerGap(31, Short.MAX_VALUE)
                .addComponent(jLabel15)
                .addGap(18, 18, 18)
                .addComponent(jLabel16)
                .addGap(38, 38, 38))
        );

        pdfBtn.setBackground(new java.awt.Color(98, 74, 134));
        pdfBtn.setToolTipText("Export to PDF");
        pdfBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pdfBtnMouseClicked(evt);
            }
        });

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/learn/icons8-PDF-64.png"))); // NOI18N

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(204, 255, 255));
        jLabel18.setText("PDF");

        javax.swing.GroupLayout pdfBtnLayout = new javax.swing.GroupLayout(pdfBtn);
        pdfBtn.setLayout(pdfBtnLayout);
        pdfBtnLayout.setHorizontalGroup(
            pdfBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pdfBtnLayout.createSequentialGroup()
                .addGroup(pdfBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pdfBtnLayout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(jLabel18))
                    .addGroup(pdfBtnLayout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(jLabel17)))
                .addContainerGap(53, Short.MAX_VALUE))
        );
        pdfBtnLayout.setVerticalGroup(
            pdfBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pdfBtnLayout.createSequentialGroup()
                .addContainerGap(31, Short.MAX_VALUE)
                .addComponent(jLabel17)
                .addGap(18, 18, 18)
                .addComponent(jLabel18)
                .addGap(38, 38, 38))
        );

        excelBtn.setBackground(new java.awt.Color(98, 74, 134));
        excelBtn.setToolTipText("Export to Excel");
        excelBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                excelBtnMouseClicked(evt);
            }
        });

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/learn/icons8-Microsoft Excel-64.png"))); // NOI18N

        jLabel20.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(204, 255, 255));
        jLabel20.setText("Excel");

        javax.swing.GroupLayout excelBtnLayout = new javax.swing.GroupLayout(excelBtn);
        excelBtn.setLayout(excelBtnLayout);
        excelBtnLayout.setHorizontalGroup(
            excelBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(excelBtnLayout.createSequentialGroup()
                .addGroup(excelBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(excelBtnLayout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(jLabel20))
                    .addGroup(excelBtnLayout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(jLabel19)))
                .addContainerGap(53, Short.MAX_VALUE))
        );
        excelBtnLayout.setVerticalGroup(
            excelBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(excelBtnLayout.createSequentialGroup()
                .addContainerGap(31, Short.MAX_VALUE)
                .addComponent(jLabel19)
                .addGap(18, 18, 18)
                .addComponent(jLabel20)
                .addGap(38, 38, 38))
        );

        javax.swing.GroupLayout panel_exportLayout = new javax.swing.GroupLayout(panel_export);
        panel_export.setLayout(panel_exportLayout);
        panel_exportLayout.setHorizontalGroup(
            panel_exportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_exportLayout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(excelBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(77, 77, 77)
                .addComponent(csvBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 89, Short.MAX_VALUE)
                .addComponent(pdfBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(74, 74, 74))
            .addGroup(panel_exportLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panel_exportLayout.setVerticalGroup(
            panel_exportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_exportLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 120, Short.MAX_VALUE)
                .addGroup(panel_exportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pdfBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(csvBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(excelBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(129, 129, 129))
        );

        jPanel3.add(panel_export, "card4");

        panel_setting.setBackground(new java.awt.Color(250, 250, 250));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel11.setForeground(java.awt.SystemColor.controlShadow);
        jLabel11.setText("Settings");

        jPanel7.setBackground(new java.awt.Color(235, 235, 235));

        jLabel24.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel24.setForeground(java.awt.SystemColor.controlShadow);
        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel24.setText("Color");

        colorLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        colorLabel.setForeground(java.awt.SystemColor.controlShadow);
        colorLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        colorLabel.setText("Current Color: Default");

        colorOption.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                colorOptionMouseEntered(evt);
            }
        });

        colorSaveBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/learn/OpacSave.png"))); // NOI18N
        colorSaveBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                colorSaveBtnMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(89, 89, 89))
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                        .addGap(0, 59, Short.MAX_VALUE)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                                .addComponent(colorOption, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(71, 71, 71))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                                .addComponent(colorSaveBtn)
                                .addGap(145, 145, 145))))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(colorLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(colorLabel)
                .addGap(26, 26, 26)
                .addComponent(colorOption, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(colorSaveBtn)
                .addContainerGap(118, Short.MAX_VALUE))
        );

        jPanel11.setBackground(new java.awt.Color(235, 235, 235));

        jLabel21.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel21.setForeground(java.awt.SystemColor.controlShadow);
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21.setText("Font Size");

        fontSizeLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        fontSizeLabel.setForeground(java.awt.SystemColor.controlShadow);
        fontSizeLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        fontSizeLabel.setText("Current Size: 14");

        fontDecreaseBtn.setBackground(new java.awt.Color(255, 255, 255));
        fontDecreaseBtn.setToolTipText("Decrease Font Size");
        fontDecreaseBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fontDecreaseBtnMouseClicked(evt);
            }
        });

        jLabel14.setBackground(new java.awt.Color(153, 255, 153));
        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("A-");

        javax.swing.GroupLayout fontDecreaseBtnLayout = new javax.swing.GroupLayout(fontDecreaseBtn);
        fontDecreaseBtn.setLayout(fontDecreaseBtnLayout);
        fontDecreaseBtnLayout.setHorizontalGroup(
            fontDecreaseBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fontDecreaseBtnLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        fontDecreaseBtnLayout.setVerticalGroup(
            fontDecreaseBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fontDecreaseBtnLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        fontInreaseBtn.setBackground(new java.awt.Color(255, 255, 255));
        fontInreaseBtn.setToolTipText("Increase Font Size");
        fontInreaseBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fontInreaseBtnMouseClicked(evt);
            }
        });

        jLabel23.setBackground(new java.awt.Color(153, 255, 153));
        jLabel23.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel23.setText("A+");

        javax.swing.GroupLayout fontInreaseBtnLayout = new javax.swing.GroupLayout(fontInreaseBtn);
        fontInreaseBtn.setLayout(fontInreaseBtnLayout);
        fontInreaseBtnLayout.setHorizontalGroup(
            fontInreaseBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fontInreaseBtnLayout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );
        fontInreaseBtnLayout.setVerticalGroup(
            fontInreaseBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fontInreaseBtnLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel23, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                .addContainerGap(84, Short.MAX_VALUE)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                        .addComponent(fontDecreaseBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24)
                        .addComponent(fontInreaseBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(108, 108, 108))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(fontSizeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(72, 72, 72))))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fontSizeLabel)
                .addGap(38, 38, 38)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(fontDecreaseBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fontInreaseBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panel_settingLayout = new javax.swing.GroupLayout(panel_setting);
        panel_setting.setLayout(panel_settingLayout);
        panel_settingLayout.setHorizontalGroup(
            panel_settingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_settingLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_settingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_settingLayout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(panel_settingLayout.createSequentialGroup()
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panel_settingLayout.setVerticalGroup(
            panel_settingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_settingLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11)
                .addGap(32, 32, 32)
                .addGroup(panel_settingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel3.add(panel_setting, "card5");

        jPanel4.setBackground(new java.awt.Color(98, 74, 134));

        secondTimer.setBackground(new java.awt.Color(253, 253, 253));
        secondTimer.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        secondTimer.setForeground(new java.awt.Color(250, 250, 250));
        secondTimer.setText(":0");

        minuteTimer.setBackground(new java.awt.Color(253, 253, 253));
        minuteTimer.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        minuteTimer.setForeground(new java.awt.Color(255, 255, 255));
        minuteTimer.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        minuteTimer.setText("00");

        startButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/learn/Start.png"))); // NOI18N
        startButton.setToolTipText("Start");
        startButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                startButtonMouseClicked(evt);
            }
        });

        projectNames.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        projectNames.setForeground(new java.awt.Color(255, 255, 255));
        projectNames.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None" }));
        projectNames.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        startDurationLabel.setBackground(new java.awt.Color(253, 253, 253));
        startDurationLabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        startDurationLabel.setForeground(new java.awt.Color(255, 255, 255));
        startDurationLabel.setText("Start Time: --");

        startDurationLabel1.setBackground(new java.awt.Color(253, 253, 253));
        startDurationLabel1.setFont(new java.awt.Font("Segoe UI", 1, 34)); // NOI18N
        startDurationLabel1.setForeground(new java.awt.Color(255, 255, 255));
        startDurationLabel1.setText("Baralga");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(startDurationLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(projectNames, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(startDurationLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(minuteTimer)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(secondTimer)
                .addGap(10, 10, 10)
                .addComponent(startButton)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(startButton)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(startDurationLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(projectNames))
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(minuteTimer, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(secondTimer)
                        .addComponent(startDurationLabel)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout bgLayout = new javax.swing.GroupLayout(bg);
        bg.setLayout(bgLayout);
        bgLayout.setHorizontalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgLayout.createSequentialGroup()
                .addComponent(sidePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        bgLayout.setVerticalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sidePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(bgLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 477, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 860, 560));

        pack();
    }// </editor-fold>//GEN-END:initComponents

     //Reset every side panel buttons when one of them is clicked
    private void btn_projectsMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_projectsMousePressed
        // TODO add your handling code here:
        setColor(btn_projects);
        resetColor(btn_dashboard);
        resetColor(btn_export);
        resetColor(btn_setting);
        resetColor(btn_setting);

        jPanel3.removeAll();
        jPanel3.repaint();
        jPanel3.revalidate();

        jPanel3.add(panel_tasks);
        jPanel3.repaint();
        jPanel3.revalidate();
        
        
    }//GEN-LAST:event_btn_projectsMousePressed

     //Reset every side panel buttons when one of them is clicked
    private void btn_dashboardMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_dashboardMousePressed
        // TODO add your handling code here:
        setColor(btn_dashboard);
        resetColor(btn_projects);
        resetColor(btn_export);
        resetColor(btn_setting);
        resetColor(btn_setting);

        jPanel3.removeAll();
        jPanel3.repaint();
        jPanel3.revalidate();

        jPanel3.add(panel_dashboard);
        jPanel3.repaint();
        jPanel3.revalidate();

    }//GEN-LAST:event_btn_dashboardMousePressed

    //Runs the timer using Timer class on another thread
    private void runTimer() {
        //Change icon to stop icon
        ImageIcon icon = new ImageIcon(getClass().getResource("/learn/Stop.png"));
        startButton.setIcon(icon);
        
        //Get current start time
        cal = Calendar.getInstance();
        startTime = sdf.format(cal.getTime());
        startDurationLabel.setText("Start Time: " + startTime);
             
        //New timer
        java.util.Timer timer = new java.util.Timer(); 
        
        //setting the counter to 10 sec
        secondCounter = 0; 
        TimerTask task = new TimerTask() {     
            
            public void run() {  
                //the timer lable to counter.
                secondTimer.setText( ":" + Integer.toString(secondCounter)); 
                secondCounter ++;
                
                // if it is 60 seconds, increments 1 to minute
                if( secondCounter == 61 ) {
                    minuteCounter++;
                    minuteTimer.setText("0" + Integer.toString(minuteCounter));
                    secondCounter = 0;
                }
                
                
                if (secondCounter == -1){
                    timer.cancel();                                       
                } else if(isIt){
                    timer.cancel();
                    isIt = false;
                }
            }
        };
        
        // =  timer.scheduleAtFixedRate(task, delay, period);
        timer.scheduleAtFixedRate(task, 1000, 1000); 
    }
    
    //Stops the timer 
    private void stopTimer() {
        //Change to icon back to start icon
        ImageIcon icon = new ImageIcon(getClass().getResource("/learn/Start.png"));
        startButton.setIcon(icon);
        
        //Get current stop time
        cal = Calendar.getInstance();
        endTime = sdf.format(cal.getTime());
        isIt = true;
        
    }
    
    //Reset every side panel buttons when one of them is clicked
    private void btn_exportMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_exportMousePressed
        // TODO add your handling code here:
        setColor(btn_export);
        resetColor(btn_dashboard);
        resetColor(btn_setting);
        resetColor(btn_setting);
        resetColor(btn_projects);
        
        jPanel3.removeAll();
        jPanel3.repaint();
        jPanel3.revalidate();

        jPanel3.add(panel_export);
        jPanel3.repaint();
        jPanel3.revalidate();
    }//GEN-LAST:event_btn_exportMousePressed

    //Reset every side panel buttons when one of them is clicked
    private void btn_settingMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_settingMousePressed
        // TODO add your handling code here:
        setColor(btn_setting);
        resetColor(btn_dashboard);
        resetColor(btn_export);
        resetColor(btn_projects);
        
        jPanel3.removeAll();
        jPanel3.repaint();
        jPanel3.revalidate();

        jPanel3.add(panel_setting);
        jPanel3.repaint();
        jPanel3.revalidate();
    }//GEN-LAST:event_btn_settingMousePressed

    //Starts timer by changing the mode to true (Timer is running)
    private void startButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_startButtonMouseClicked
        
        //Check whether a project is created before starting the timer
        if( projectNames.getSelectedItem().toString().equals("None") ) {
            JOptionPane.showMessageDialog(null, "Please select a project first", "Can't Save" , JOptionPane.INFORMATION_MESSAGE);
        } else {
            if( !mode ) {
                runTimer();
                mode = true;
            } else if( mode ) {
                stopTimer();
                mode = false;
            }
        }


        
    }//GEN-LAST:event_startButtonMouseClicked

    //Shows add new project box
    private void btn_AddMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_AddMouseClicked

        NewWindow w = new NewWindow(this);
        w.setVisible(true);
        

    }//GEN-LAST:event_btn_AddMouseClicked

    /*
        Save a task by first checking:
        whether a project is selected or created,
        or task description is entered, 
        or the timer is already started.
    **/
    private void btn_saveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_saveMouseClicked


        if( projectNames.getSelectedItem().toString().equals("None") ) {
            JOptionPane.showMessageDialog(null, "Please select a project first", "Can't Save" , JOptionPane.INFORMATION_MESSAGE);
        } else if( descriptionTextField.getText().equals("Task Description Here...") ) {
            JOptionPane.showMessageDialog(null, "Please enter task description before saving", "Can't Save" , JOptionPane.INFORMATION_MESSAGE);
        } else if ( minuteCounter == 0 && secondCounter == 0) {
            JOptionPane.showMessageDialog(null, "Please start the timer before saving", "Timer" , JOptionPane.INFORMATION_MESSAGE);

        } else {

            //Change mode to stop when a task is successfully saved
            if( mode ) {
                stopTimer();
                mode = false;
            }
            
            //Get current time to be recorded in task details
            DefaultTableModel model = (DefaultTableModel) dataTable.getModel();

            DateTimeFormatter dtf = DateTimeFormatter.ofPattern("dd/MM/yyyy");
            LocalDate localDate = LocalDate.now();

            //Calculate total time taken and then reset those labels
            if( minuteCounter == 0 ) {
                totalHours = totalHours + 0.1;
                Object[] row = { descriptionTextField.getText(), dtf.format(localDate), startTime, endTime, "0." + Integer.toString(1) };
                model.addRow(row);
            } else {
                totalHours = totalHours + minuteCounter;
                Object[] row = { descriptionTextField.getText(), dtf.format(localDate), startTime, endTime, Integer.toString(minuteCounter) };
                model.addRow(row);
            }

            //Reset labels here
            totalHoursLbl.setText(Double.toString(totalHours));
            minuteCounter = 0;
            secondCounter = 0;

            minuteTimer.setText("0" + Integer.toString(minuteCounter));
            secondTimer.setText( ":" + Integer.toString(secondCounter));
            categoryLabel.setVisible(true);
            pieLabel.setVisible(true);

            startDurationLabel.setText("Start Time: --");
            descriptionTextField.setText("Task Description Here...");
            
            ImageIcon icon = new ImageIcon(getClass().getResource("/learn/OpacSave.png"));
            btn_save.setIcon(icon);
            
            JOptionPane.showMessageDialog(null, "Saved!", "" , JOptionPane.INFORMATION_MESSAGE);
            

        }

    }//GEN-LAST:event_btn_saveMouseClicked

    //Change icons when a task is saved
    private void descriptionTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_descriptionTextFieldKeyTyped
        // TODO add your handling code here:
        
        if( !( projectNames.getSelectedItem().toString().equals("None") ) ){
            ImageIcon icon = new ImageIcon(getClass().getResource("/learn/Save.png"));
            btn_save.setIcon(icon);
        }
       
    }//GEN-LAST:event_descriptionTextFieldKeyTyped

    //Increase the font size
    private void fontInreaseBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fontInreaseBtnMouseClicked

        defaultFontSize += 2;
        fontSizeLabel.setText("Current Size: " + defaultFontSize);
        
    }//GEN-LAST:event_fontInreaseBtnMouseClicked

    //Decrease the font size
    private void fontDecreaseBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fontDecreaseBtnMouseClicked

        defaultFontSize -= 2;
        fontSizeLabel.setText("Current Size: " + defaultFontSize);
    }//GEN-LAST:event_fontDecreaseBtnMouseClicked

    private void colorSaveBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_colorSaveBtnMouseClicked
        
        
        String selectedColor = colorOption.getSelectedItem();
        colorLabel.setText("Current Color: " + selectedColor);
        defaultColor = selectedColor;
        ImageIcon icon = new ImageIcon(getClass().getResource("/learn/OpacSave.png"));
        colorSaveBtn.setIcon(icon);
        
        JOptionPane.showMessageDialog(null, "Saved!", "" , JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_colorSaveBtnMouseClicked

    private void colorOptionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_colorOptionMouseEntered
        // TODO add your handling code here:
        String selectedColor = colorOption.getSelectedItem();
        System.out.println("selected" + selectedColor);
        if( !( selectedColor.equals(defaultColor) ) ) {
            ImageIcon icon = new ImageIcon(getClass().getResource("/learn/Save.png"));
            colorSaveBtn.setIcon(icon);
        }
    }//GEN-LAST:event_colorOptionMouseEntered

    private void excelBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_excelBtnMouseClicked
        printExportMsgBox();
    }//GEN-LAST:event_excelBtnMouseClicked

    private void csvBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_csvBtnMouseClicked
        printExportMsgBox();
    }//GEN-LAST:event_csvBtnMouseClicked

    private void pdfBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pdfBtnMouseClicked
        printExportMsgBox();
    }//GEN-LAST:event_pdfBtnMouseClicked
  
    public void printExportMsgBox() {
        JOptionPane.showMessageDialog(null, "Exported!", "" , JOptionPane.INFORMATION_MESSAGE);
    }
    //Save project and increase the total number of projects 
    public void saveNewProject() {
        
        projectCounter++;
        this.projectNames.addItem(newProjectName);
        this.projectNames.setSelectedIndex(projectCounter);

    }
    
    //Set color whenever a side panel button is clicked
    void setColor(JPanel panel) {
        panel.setBackground(new Color(85,65,118));
    }
    
    //Reset color whenever a side panel button is clicked
    void resetColor(JPanel panel) {
        panel.setBackground(new Color(64,43,100));
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws InterruptedException {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HCIGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HCIGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HCIGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HCIGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                new HCIGUI().setVisible(true);
                
            }
        });
        

    }

    private javax.swing.JTextField new_projectTextField;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bg;
    private javax.swing.JLabel btn_Add;
    private javax.swing.JPanel btn_dashboard;
    private javax.swing.JPanel btn_export;
    private javax.swing.JPanel btn_projects;
    private javax.swing.JLabel btn_save;
    private javax.swing.JPanel btn_setting;
    private javax.swing.JLabel categoryLabel;
    private javax.swing.JLabel colorLabel;
    private java.awt.Choice colorOption;
    private javax.swing.JLabel colorSaveBtn;
    private javax.swing.JPanel csvBtn;
    private javax.swing.JTable dataTable;
    private javax.swing.JTextField descriptionTextField;
    private javax.swing.JPanel excelBtn;
    private javax.swing.JPanel fontDecreaseBtn;
    private javax.swing.JPanel fontInreaseBtn;
    private javax.swing.JLabel fontSizeLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel minuteTimer;
    private java.awt.Choice optionChoice;
    private javax.swing.JPanel panel_dashboard;
    private javax.swing.JPanel panel_export;
    private javax.swing.JPanel panel_setting;
    private javax.swing.JPanel panel_tasks;
    private javax.swing.JPanel pdfBtn;
    private javax.swing.JLabel pieLabel;
    private javax.swing.JComboBox<String> projectNames;
    private javax.swing.JLabel secondTimer;
    private javax.swing.JPanel sidePanel;
    private javax.swing.JLabel startButton;
    private javax.swing.JLabel startDurationLabel;
    private javax.swing.JLabel startDurationLabel1;
    private javax.swing.JLabel totalHoursLbl;
    // End of variables declaration//GEN-END:variables
}
